# -evaluation
# --FrozenLake-v1
# ---task_decomposition
# ----zero_shot
# -----stats.json
# ----four_shot
# -----stats.json
# ----eight_shot
# -----stats.json
# ----sixteen_shot
# -----stats.json
# ---multi_plan_selection
# ----zero_shot
# -----stats.json
# ----dour_shot
# -----stats.json
# ----eight_shot
# -----stats.json
# ----sixteen_shot
# -----stats.json
# ---reflection_refinement
# ----zero_shot
# -----stats.json
# ----four_shot
# -----stats.json
# ----eight_shot
# -----stats.json
# ----sixteen_shot
# -----stats.json